# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/

---

development:
  api_key: 2f1979b64fd471f8692c920838ab735a
  password: e6b8f159238f02584327577ca8ec1a2e
  theme_id: 46204846198
  store: o-wool-stage.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

production:
  api_key:
  password:
  theme_id: "live"
  store:
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings
